# 排除不必要的目录
exclude:
  - node_modules/
  - meow/node_modules/
  - .git/
  - .github/
  - vendor/
  - bower_components/
  - Gemfile
  - Gemfile.lock
  - android/
  - capacitor.config.ts
  - package.json
  - package-lock.json
  - www/
  - *.log
  - .DS_Store

# 使用捆绑的 Python 版本
use_bundled_python: true