// 品牌数据
const brandData = {
    "护肤品": [
        {name: "郁美净", logo: "logos/skincare/yumeijing.png",  description: "专注于温和护肤，适合各种肤质使用的经典国货品牌。", founded: "1980年", city: "天津", honors: "中国名牌产品、国家免检产品", reputation: "国民级婴幼儿护肤品，以郁美净儿童霜闻名，温和安全，口碑极佳。"},
        {name: "百雀羚", logo: "logos/skincare/baiqueling.png", description: "拥有80多年历史的老牌国货，以草本护肤著称。", founded: "1931年", city: "上海", honors: "中国驰名商标、上海市著名商标", reputation: "老牌国货典范，产品线丰富，草本配方温和有效，深受各年龄段消费者喜爱。"},
        {name: "相宜本草", logo: "logos/skincare/xiangyibencao.png", description: "采用中医药理论研制的天然草本护肤品。", founded: "2000年", city: "上海", honors: "中国化妆品行业领军企业", reputation: "将中医药理念与现代科技结合，产品天然温和，性价比高，口碑良好。"},
        {name: "丁家宜", logo: "logos/skincare/dingjiayi.png", description: "专注于美白护肤，产品温和有效。", founded: "1995年", city: "苏州", honors: "中国化妆品行业知名品牌", reputation: "以美白产品著称，配方温和，效果显著，深受女性消费者青睐。"},
        {name: "佰草集", logo: "logos/skincare/herborist.png", description: "高端草本护肤品牌，融合传统中医理念。", founded: "1998年", city: "上海", honors: "中国高端护肤品代表品牌", reputation: "将中国传统草药精华与现代科技完美结合，产品高端定位，品质卓越。"},
        {name: "韩束", logo: "logos/skincare/kanebao.png", description: "主打补水保湿的现代护肤品牌。", founded: "2002年", city: "上海", honors: "中国化妆品行业影响力品牌", reputation: "以补水保湿产品为主，科技创新，产品线丰富，年轻消费者喜爱。"},
        {name: "双妹", logo: "logos/skincare/shuangmei.png", description: "百年历史的高端护肤品牌，重现东方美。", founded: "1898年", city: "上海", honors: "中国历史文化名品", reputation: "百年老牌，东方美学代表，产品高端奢华，传承经典配方。"},
        {name: "美加净", logo: "logos/skincare/maxam.png", description: "经典国货，以护手霜和面霜闻名。", founded: "1962年", city: "上海", honors: "中国驰名商标", reputation: "国民级护肤品牌，护手霜和面霜口碑极佳，性价比高。"},
        {name: "欧诗漫", logo: "logos/skincare/osm.png", description: "珍珠护肤专家，专注于珍珠美白产品。", founded: "1967年", city: "浙江湖州", honors: "中国珍珠护肤领导品牌", reputation: "珍珠护肤专家，产品温和有效，美白保湿效果显著。"},
        {name: "采诗", logo: "logos/skincare/caishi.png", description: "平价护肤品牌，适合学生党使用。", founded: "1997年", city: "广东广州", honors: "中国化妆品行业知名品牌", reputation: "平价路线，产品多样，适合年轻消费者，性价比极高。"},
        {name: "珀莱雅", logo: "logos/skincare/proya.png", description: "海洋护肤理念，主打深层补水。", founded: "2003年", city: "浙江杭州", honors: "中国化妆品行业领军企业", reputation: "海洋护肤理念，产品补水保湿效果好，年轻时尚，口碑良好。"},
        {name: "水密码", logo: "logos/skincare/wetcode.png", description: "专注于补水保湿的护肤品品牌。", founded: "2008年", city: "广东广州", honors: "中国补水护肤领导品牌", reputation: "以补水保湿为核心，产品清爽不油腻，深受年轻女性喜爱。"},
        {name: "润本", logo: "logos/skincare/runben.png", description: "温和无刺激，适合敏感肌肤使用。", founded: "2006年", city: "广东广州", honors: "中国母婴护理知名品牌", reputation: "产品温和无刺激，适合婴幼儿和敏感肌，安全可靠。"},
        {name: "启初", logo: "logos/skincare/giving.png", description: "婴儿和成人敏感肌护理专家。", founded: "2013年", city: "上海", honors: "中国婴幼儿护理领先品牌", reputation: "专为中国宝宝研发，产品温和安全，敏感肌成人也可使用。"},
        {name: "薇诺娜", logo: "logos/skincare/winona.png", description: "专注于敏感肌肤护理的医学护肤品牌。", founded: "2008年", city: "云南昆明", honors: "中国医学护肤领导品牌", reputation: "针对敏感肌肤研发，医学背景强，产品安全有效，口碑极佳。"},
        {name: "高姿", logo: "logos/skincare/gogir.png", description: "以美白和保湿为主打的护肤品牌。", founded: "1984年", city: "上海", honors: "中国化妆品行业知名品牌", reputation: "美白保湿产品效果显著，性价比高，深受消费者喜爱。"},
        {name: "健美创研", logo: "logos/skincare/jianmeichuangyan.png", description: "平价而多样化的护肤和彩妆品牌。", founded: "2011年", city: "广东广州", honors: "中国新锐美妆品牌", reputation: "产品多样，价格亲民，适合学生党和年轻消费者。"},
        {name: "馥珮", logo: "logos/skincare/fupei.png", description: "结合草本精华的护肤和个人护理品牌。", founded: "1993年", city: "广西柳州", honors: "中国化妆品行业知名品牌", reputation: "草本配方，产品温和有效，个人护理系列丰富。"},
        {name: "京润", logo: "logos/skincare/jingrun.png", description: "珍珠护肤专家，产品天然温和。", founded: "1994年", city: "海南海口", honors: "中国珍珠护肤知名品牌", reputation: "海南珍珠资源优势，产品天然温和，珍珠美白效果好。"},
        {name: "御泥坊", logo: "logos/skincare/yunixiang.png", description: "以矿物泥面膜闻名的护肤品牌。", founded: "2006年", city: "湖南长沙", honors: "中国面膜行业领导品牌", reputation: "矿物泥面膜口碑极佳，清洁保湿效果好，年轻人喜爱。"},
        {name: "大水滴", logo: "logos/skincare/dashuidi.png", description: "专注于控油和痘痘肌护理。", founded: "2018年", city: "上海", honors: "中国新锐护肤品牌", reputation: "针对痘痘肌和油性肌肤，产品控油效果好，深受年轻消费者欢迎。"},
        {name: "花瑶花", logo: "logos/skincare/huayaohua.png", description: "以花精华为主要成分的护肤品牌。", founded: "2011年", city: "上海", honors: "中国天然护肤新锐品牌", reputation: "花精华为核心，产品天然温和，花香宜人，用户评价好。"},
        {name: "美肤宝", logo: "logos/skincare/meifubao.png", description: "温和护肤，适合各种肤质。", founded: "1999年", city: "广东广州", honors: "中国化妆品行业知名品牌", reputation: "产品温和不刺激，适合各种肤质，价格适中，口碑稳定。"},
        {name: "法兰琳卡", logo: "logos/skincare/franic.png", description: "天然有机护肤理念的代表品牌。", founded: "2002年", city: "广东广州", honors: "中国有机护肤领先品牌", reputation: "天然有机理念，产品温和安全，深受环保人士喜爱。"},
        {name: "林清轩", logo: "logos/skincare/forest cabin.png", description: "以山茶花油为核心成分的高端护肤品牌。", founded: "2003年", city: "上海", honors: "中国高端护肤新锐品牌", reputation: "山茶花油为核心，产品高端定位，品质卓越，口碑良好。"},
        {name: "永芳", logo: "logos/skincare/yongfang.png", description: "老牌国货，以珍珠膏闻名。", founded: "1942年", city: "新加坡（华人创办）", honors: "东南亚知名华人品牌", reputation: "老牌珍珠膏闻名，滋润保湿效果好，深受中老年人喜爱。"},
        {name: "衡美肤", logo: "logos/skincare/hengmeifu.png", description: "平衡肌肤状态的护肤品牌。", founded: "2010年", city: "广东广州", honors: "中国药妆护肤新锐品牌", reputation: "平衡肌肤理念，产品温和有效，适合问题肌肤使用。"},
        {name: "月里嫦娥", logo: "logos/skincare/yuelichange.png", description: "专注于夜间修护的护肤品牌。", founded: "2015年", city: "江苏苏州", honors: "中国新锐护肤品牌", reputation: "夜间修护理念，产品质地细腻，修护效果好，口碑良好。"},
        {name: "七日香", logo: "logos/skincare/qirixiang.png", description: "经典老牌，产品温和滋润。", founded: "1937年", city: "广东广州", honors: "中国老牌护肤名品", reputation: "老牌国货，产品温和滋润，价格亲民，深受中老年人喜爱。"},
        {name: "春娟", logo: "logos/skincare/chunjuan.png", description: "以黄芪为主要成分的护肤品牌。", founded: "1980年", city: "四川成都", honors: "四川省著名商标", reputation: "黄芪草本配方，产品温和滋润，适合敏感肌，口碑稳定。"},
        {name: "雅霜", logo: "logos/skincare/yashuang.png", description: "传统面霜品牌，具有浓郁的怀旧气息。", founded: "1932年", city: "上海", honors: "中国历史文化名品", reputation: "经典怀旧面霜，香气独特，滋润效果好，中老年消费者喜爱。"},
        {name: "迷奇", logo: "logos/skincare/micky.png", description: "出口日本的高品质护肤品牌。", founded: "1987年", city: "北京", honors: "中国出口免检产品", reputation: "产品品质高，曾出口日本市场，口碑良好，性价比高。"},
        {name: "兰亭", logo: "logos/skincare/lanting.png", description: "专注于天然成分的护肤品牌。", founded: "1993年", city: "浙江宁波", honors: "中国化妆品行业知名品牌", reputation: "天然成分理念，产品温和安全，价格适中，用户评价好。"},
        {name: "万紫千红", logo: "logos/skincare/wanziqianhong.png", description: "经典老牌护肤脂，滋润保湿效果好。", founded: "1950年", city: "天津", honors: "中国老牌护肤名品", reputation: "经典护肤脂，滋润保湿效果极佳，冬季必备，价格亲民。"},
        {name: "京卫本草", logo: "logos/skincare/jingweibencao.png", description: "医院研制的药妆品牌，安全有效。", founded: "1998年", city: "北京", honors: "中国药妆领先品牌", reputation: "军事医学科学院研制，产品安全有效，针对各种肌肤问题。"},
        {name: "宫灯", logo: "logos/skincare/gongdeng.png", description: "老牌国货，以杏仁蜜闻名。", founded: "1963年", city: "上海", honors: "中国老牌护肤名品", reputation: "杏仁蜜经典产品，滋润保湿，价格亲民，口碑良好。"},
        {name: "森宝", logo: "logos/skincare/senbao.png", description: "天然植物护肤理念的品牌。", founded: "2005年", city: "浙江杭州", honors: "中国天然护肤新锐品牌", reputation: "天然植物配方，产品温和安全，环保理念，用户评价好。"},
        {name: "西施美", logo: "logos/skincare/xishimei.png", description: "传统中药护肤配方的代表。", founded: "1980年", city: "浙江诸暨", honors: "中国中药护肤知名品牌", reputation: "传统中药配方，产品温和有效，适合各种肤质。"},
        {name: "标婷", logo: "logos/skincare/biaoting.png", description: "医院研制的维生素E乳等产品。", founded: "1993年", city: "北京", honors: "北京医院研制", reputation: "北京医院研制，维生素E乳口碑极佳，滋润保湿，价格亲民。"},
        {name: "孔凤春", logo: "logos/skincare/kongfengchun.png", description: "百年历史的老字号护肤品牌。", founded: "1862年", city: "浙江杭州", honors: "中国历史文化名品", reputation: "百年老字号，传统配方，产品温和有效，深受消费者信赖。"},
        {name: "戴春林", logo: "logos/skincare/daichunlin.png", description: "三百多年历史的传统美妆品牌。", founded: "1628年", city: "江苏扬州", honors: "中国历史文化名品", reputation: "三百多年历史，传统工艺，产品天然安全，文化底蕴深厚。"},
        {name: "片仔癀", logo: "logos/skincare/pianzaihuang.png", description: "中药护肤专家，具有祛痘功效。", founded: "1980年", city: "福建漳州", honors: "中国驰名商标、国家非物质文化遗产", reputation: "漳州片仔癀为核心成分，祛痘效果显著，口碑极佳。"},
        {name: "隆力奇", logo: "logos/skincare/longrich.png", description: "多元化的日化品牌，产品线丰富。", founded: "1986年", city: "江苏常熟", honors: "中国驰名商标", reputation: "产品线丰富，从个人护理到家居清洁，性价比高，市场占有率高。"},
        {name: "东洋之花", logo: "logos/skincare/dongyangzhihua.png", description: "专注于基础护肤的品牌。", founded: "1992年", city: "江苏南通", honors: "中国化妆品行业知名品牌", reputation: "基础护肤为主，产品温和有效，价格亲民，适合大众消费。"},
        {name: "青蛙王子", logo: "logos/skincare/frogprince.png", description: "儿童护肤专家，产品温和无刺激。", founded: "1999年", city: "福建漳州", honors: "中国儿童护理领导品牌", reputation: "儿童护理专家，产品温和无刺激，安全可靠，家长信赖。"},
        {name: "孩儿面", logo: "logos/skincare/haiermian.png", description: "经典儿童护肤品牌，产品可爱有效。", founded: "1994年", city: "上海", honors: "中国儿童护理知名品牌", reputation: "经典儿童面霜，包装可爱，产品温和有效，深受儿童和家长喜爱。"},
        {name: "红色小象", logo: "logos/skincare/hongsexiaoxiang.png", description: "高端母婴护肤品牌。", founded: "2015年", city: "上海", honors: "中国高端母婴护理领先品牌", reputation: "高端母婴护理，产品安全温和，定位中高端，口碑良好。"},
        {name: "贝倍舒", logo: "logos/skincare/beibeishu.png", description: "专注于婴幼儿护肤的品牌。", founded: "2002年", city: "江苏无锡", honors: "中国婴幼儿护理知名品牌", reputation: "专注婴幼儿护肤，产品温和安全，针对婴幼儿肌肤特点研发。"},
        {name: "精心", logo: "logos/skincare/jingxin.png", description: "医院研制的护肤品，安全可靠。", founded: "1992年", city: "北京", honors: "北京协和医院研制", reputation: "北京协和医院研制，产品安全可靠，针对敏感肌，口碑极佳。"},
        {name: "汉和中方", logo: "logos/skincare/hanhezhongfang.png", description: "融合中医理论的护肤品牌。", founded: "2012年", city: "广东广州", honors: "中国中药护肤新锐品牌", reputation: "中医理论与现代科技结合，产品温和有效，适合各种肤质。"},
        {name: "安安", logo: "logos/skincare/an'an.png", description: "平价而有效的护肤品牌。", founded: "1985年", city: "广东佛山", honors: "广东省著名商标", reputation: "平价路线，产品多样，效果可靠，深受大众喜爱。"},
        {name: "植物主义", logo: "logos/skincare/zhiwuzhuyi.png", description: "天然植物成分的护肤品牌。", founded: "2014年", city: "山东青岛", honors: "中国天然护肤新锐品牌", reputation: "天然植物成分，产品温和安全，适合敏感肌，环保理念。"},
        {name: "半亩花田", logo: "logos/skincare/banmuhuatian.png", description: "以身体护理产品为主的护肤品牌。", founded: "2010年", city: "山东济南", honors: "中国身体护理领先品牌", reputation: "身体护理产品口碑极佳，尤其是磨砂膏和身体乳，价格适中。"},
        {name: "五羊", logo: "logos/skincare/wuyang.png", description: "专注于母婴护理的品牌。", founded: "1920年", city: "广东广州", honors: "中国母婴护理知名品牌", reputation: "百年历史，专注母婴护理，产品温和安全，深受妈妈们信赖。"},
        {name: "至本", logo: "logos/skincare/zhiben.png", description: "专注于修护和敏感肌护理的品牌。", founded: "2012年", city: "上海", honors: "中国敏感肌护理新锐品牌", reputation: "专注敏感肌和修护，产品温和有效，包装简约，口碑极佳。"},
        {name: "润百颜", logo: "logos/skincare/runbaiyan.png", description: "玻尿酸护肤专家，专注于保湿。", founded: "2012年", city: "山东济南", honors: "中国玻尿酸护肤领导品牌", reputation: "玻尿酸专家，产品保湿效果好，科技感强，用户评价高。"},
        {name: "无双", logo: "logos/skincare/wushuang.png", description: "新兴国货护肤品牌，产品创新。", founded: "2019年", city: "上海", honors: "中国新锐护肤品牌", reputation: "新兴品牌，产品创新，包装设计独特，深受年轻消费者喜爱。"}
    ],
    "美妆类": [
        {name: "稚优泉", logo: "logos/cosmetics/zhiyouquan.png", description: "年轻时尚的彩妆品牌，性价比高。", founded: "2010年", city: "上海", honors: "中国新锐彩妆品牌", reputation: "年轻时尚，价格亲民，产品更新快，深受学生党和年轻女性喜爱。"},
        {name: "蔻也", logo: "logos/cosmetics/kouye.png", description: "专注于眼妆产品的彩妆品牌。", founded: "2018年", city: "广东深圳", honors: "中国眼妆新锐品牌", reputation: "专注眼妆，产品创新，色彩丰富，年轻消费者喜爱。"},
        {name: "美康粉黛", logo: "logos/cosmetics/meikangfendai.png", description: "古典风格的彩妆品牌，包装精美。", founded: "2012年", city: "江苏南京", honors: "中国古典美妆代表品牌", reputation: "中国风包装，产品古典雅致，性价比高，适合喜欢传统美学的消费者。"},
        {name: "花落利亚", logo: "logos/cosmetics/hualuoliya.png", description: "新兴国货彩妆品牌，产品丰富。", founded: "2019年", city: "广东广州", honors: "中国彩妆新锐品牌", reputation: "新兴品牌，产品丰富，价格亲民，包装可爱，年轻女性喜爱。"},
        {name: "卡婷", logo: "logos/cosmetics/kating.png", description: "中国风彩妆品牌，包装极具特色。", founded: "2012年", city: "广东广州", honors: "中国风彩妆领导品牌", reputation: "中国风设计突出，包装精美，产品质量好，口碑极佳。"},
        {name: "戈戈舞", logo: "logos/cosmetics/gegewu.png", description: "平价而时尚的彩妆品牌。", founded: "2016年", city: "广东广州", honors: "中国平价彩妆知名品牌", reputation: "平价时尚，产品更新快，适合学生党和年轻消费者。"},
        {name: "花知晓", logo: "logos/cosmetics/huazhixiao.png", description: "高颜值包装的彩妆品牌，少女心十足。", founded: "2016年", city: "浙江杭州", honors: "中国高颜值彩妆代表品牌", reputation: "包装精美梦幻，少女心十足，产品质量好，深受年轻女性喜爱。"},
        {name: "毛戈平", logo: "logos/cosmetics/maogeping.png", description: "高端专业彩妆品牌，品质卓越。", founded: "2000年", city: "浙江杭州", honors: "中国高端彩妆领导品牌", reputation: "专业彩妆大师创办，产品品质卓越，适合专业化妆师和高端消费者。"},
        {name: "谢馥春", logo: "logos/cosmetics/xiefuchun.png", description: "百年历史的传统美妆品牌。", founded: "1830年", city: "江苏扬州", honors: "中国历史文化名品", reputation: "百年老字号，传统工艺，产品天然安全，文化底蕴深厚。"},
        {name: "孔凤春", logo: "logos/cosmetics/kongfengchun.png", description: "传统国货美妆品牌，有悠久历史。", founded: "1862年", city: "浙江杭州", honors: "中国历史文化名品", reputation: "百年老字号，传统配方，产品温和有效，深受消费者信赖。"},
        {name: "戴春林", logo: "logos/cosmetics/daichunlin.png", description: "三百多年历史的传统美妆品牌。", founded: "1628年", city: "江苏扬州", honors: "中国历史文化名品", reputation: "三百多年历史，传统工艺，产品天然安全，文化底蕴深厚。"},
        {name: "卡姿兰", logo: "logos/cosmetics/kazilan.png", description: "知名彩妆品牌，产品线全面。", founded: "2001年", city: "广东深圳", honors: "中国彩妆行业领军企业", reputation: "产品线全面，色彩丰富，性价比高，市场占有率高。"},
        {name: "火烈鸟", logo: "logos/cosmetics/huolieniao.png", description: "以睫毛膏闻名的彩妆品牌。", founded: "2000年", city: "上海", honors: "中国睫毛膏领导品牌", reputation: "睫毛膏口碑极佳，浓密纤长效果好，价格亲民。"},
        {name: "玛丽黛佳", logo: "logos/cosmetics/malidaidai.png", description: "创新彩妆品牌，注重产品体验。", founded: "2006年", city: "上海", honors: "中国彩妆行业创新品牌", reputation: "产品创新，体验感好，包装设计独特，年轻消费者喜爱。"},
        {name: "ZFC", logo: "logos/cosmetics/zfc.png", description: "专业彩妆品牌，适合化妆师使用。", founded: "2004年", city: "广东深圳", honors: "中国专业彩妆知名品牌", reputation: "专业彩妆，品质可靠，适合化妆师和专业场合使用。"},
        {name: "凯芙兰", logo: "logos/cosmetics/kaifulan.png", description: "时尚彩妆品牌，产品色彩丰富。", founded: "2008年", city: "广东深圳", honors: "中国时尚彩妆知名品牌", reputation: "时尚色彩，产品丰富，适合年轻女性，性价比高。"},
        {name: "深蓝", logo: "logos/cosmetics/shenlan.png", description: "专业彩妆品牌，品质可靠。", founded: "2000年", city: "上海", honors: "中国专业彩妆领先品牌", reputation: "专业彩妆，品质可靠，色彩饱满，适合专业化妆需求。"},
        {name: "俏美人", logo: "logos/cosmetics/qiaomeiren.png", description: "平价彩妆品牌，性价比高。", founded: "2005年", city: "广东广州", honors: "中国平价彩妆知名品牌", reputation: "平价路线，产品多样，适合学生党和年轻消费者。"},
        {name: "霞飞", logo: "logos/cosmetics/xiafei.png", description: "老牌彩妆品牌，经典回归。", founded: "1985年", city: "上海", honors: "中国老牌彩妆名品", reputation: "老牌回归，经典产品，价格亲民，品质可靠。"},
        {name: "兰瑟", logo: "logos/cosmetics/lanse.png", description: "中高端彩妆品牌，产品质感好。", founded: "2006年", city: "广东深圳", honors: "中国中高端彩妆知名品牌", reputation: "中高端定位，产品质感好，持久度高，适合成熟女性。"},
        {name: "Gracebabi", logo: "logos/cosmetics/gracebabi.png", description: "专注于美妆工具的品牌。", founded: "2013年", city: "江苏苏州", honors: "中国美妆工具领先品牌", reputation: "美妆工具专业品牌，刷子质量好，性价比高，深受化妆师喜爱。"},
        {name: "花西子", logo: "logos/cosmetics/huaxizi.png", description: "高端中国风彩妆品牌，口碑极佳。", founded: "2017年", city: "浙江杭州", honors: "中国高端彩妆新锐品牌", reputation: "中国风高端彩妆，产品品质卓越，包装精美，口碑极佳。"},
        {name: "格蕾丝宝贝", logo: "logos/cosmetics/geleisibaobei.png", description: "美妆工具品牌，刷子质量好。", founded: "2015年", city: "广东广州", honors: "中国美妆工具新锐品牌", reputation: "美妆工具质量好，价格适中，用户评价高。"},
        {name: "诗佩妮", logo: "logos/cosmetics/shipeini.png", description: "平价彩妆品牌，眼影盘备受好评。", founded: "2012年", city: "广东广州", honors: "中国平价彩妆知名品牌", reputation: "眼影盘性价比极高，色彩饱满，适合彩妆新手。"},
        {name: "料堆堆", logo: "logos/cosmetics/liaoduoduo.png", description: "新兴彩妆品牌，产品创新。", founded: "2020年", city: "上海", honors: "中国彩妆新锐品牌", reputation: "新兴品牌，产品创新，包装独特，年轻消费者喜爱。"},
        {name: "儒意", logo: "logos/cosmetics/ruyi.png", description: "多元化的美妆品牌。", founded: "2018年", city: "广东广州", honors: "中国美妆新锐品牌", reputation: "产品多元化，覆盖彩妆和护肤，性价比高，用户评价好。"},
        {name: "卡奇", logo: "logos/cosmetics/kaji.png", description: "彩妆品牌，产品多样化。", founded: "2016年", city: "广东深圳", honors: "中国彩妆新锐品牌", reputation: "产品多样化，色彩丰富，价格亲民，适合年轻消费者。"},
        {name: "梦鹿", logo: "logos/cosmetics/menglu.png", description: "美妆工具品牌，性价比高。", founded: "2015年", city: "浙江杭州", honors: "中国美妆工具新锐品牌", reputation: "美妆工具性价比高，质量可靠，深受学生党喜爱。"},
        {name: "佩冉", logo: "logos/cosmetics/peiran.png", description: "新兴彩妆品牌，注重产品质量。", founded: "2019年", city: "上海", honors: "中国彩妆新锐品牌", reputation: "新兴品牌，注重产品质量，效果持久，口碑良好。"},
        {name: "razo", logo: "logos/cosmetics/razo.png", description: "彩妆品牌，产品设计时尚。", founded: "2018年", city: "广东深圳", honors: "中国彩妆新锐品牌", reputation: "产品设计时尚，色彩潮流，适合追求个性的年轻消费者。"},
        {name: "novo", logo: "logos/cosmetics/novo.png", description: "平价彩妆品牌，产品更新快。", founded: "2014年", city: "广东广州", honors: "中国平价彩妆知名品牌", reputation: "产品更新快，紧跟潮流，价格极低，适合尝试不同妆容。"},
        {name: "jillleen", logo: "logos/cosmetics/jillleen.png", description: "小众彩妆品牌，单品出色。", founded: "2015年", city: "浙江杭州", honors: "中国小众彩妆知名品牌", reputation: "小众精品，单品质量出色，尤其是高光和腮红，口碑极佳。"},
        {name: "橘", logo: "logos/cosmetics/ju.png", description: "专注于橘色调彩妆的品牌。", founded: "2019年", city: "上海", honors: "中国彩妆新锐品牌", reputation: "专注橘色调，色彩鲜艳，适合暖皮人群，年轻时尚。"},
        {name: "滋色", logo: "logos/cosmetics/zise.png", description: "时尚彩妆品牌，产品种类丰富。", founded: "2013年", city: "广东广州", honors: "中国时尚彩妆知名品牌", reputation: "产品种类丰富，色彩时尚，价格适中，年轻消费者喜爱。"},
        {name: "完美日记", logo: "logos/cosmetics/wanmeiriji.png", description: "知名国货彩妆品牌，产品线全面。", founded: "2016年", city: "广东广州", honors: "中国彩妆行业领军企业", reputation: "产品线全面，产品创新，营销出色，年轻消费者首选品牌之一。"},
        {name: "尤西斯", logo: "logos/cosmetics/yousixi.png", description: "新兴彩妆品牌，产品独特。", founded: "2020年", city: "上海", honors: "中国彩妆新锐品牌", reputation: "产品独特，概念新颖，包装设计感强，深受潮流人士喜爱。"}
    ],
    "洗发水": [
        {name: "蜂花", logo: "logos/shampoo/fenghua.png", description: "经典国货洗护发品牌，以护发素闻名。", founded: "1985年", city: "上海", honors: "中国名牌产品", reputation: "经典老牌，产品温和有效，价格亲民，护发素口碑极佳。"},
        {name: "馥佩", logo: "logos/shampoo/fupei.png", description: "专注于天然植物洗护的品牌。", founded: "2000年", city: "广东广州", honors: "中国植物洗护知名品牌", reputation: "天然植物配方，温和不刺激，适合各种发质，性价比高。"},
        {name: "霸王", logo: "logos/shampoo/bawang.png", description: "专注于防脱发和乌发的洗护品牌。", founded: "1928年", city: "广东广州", honors: "中国防脱发领导品牌", reputation: "中药配方，防脱发效果好，口碑极佳，深受中老年消费者喜爱。"},
        {name: "蒂花之秀", logo: "logos/shampoo/dihuazhixiu.png", description: "时尚洗护发品牌，产品线全面。", founded: "1993年", city: "广东汕头", honors: "中国洗护行业知名品牌", reputation: "产品线全面，适合各种发质，价格适中，年轻消费者喜爱。"},
        {name: "亮荘", logo: "logos/shampoo/liangzhuang.png", description: "专注于男士洗护的品牌。", founded: "2000年", city: "广东广州", honors: "中国男士洗护领先品牌", reputation: "男士洗护专业，控油效果好，价格适中，口碑良好。"},
        {name: "拉芳", logo: "logos/shampoo/lafang.png", description: "知名洗护发品牌，产品多样化。", founded: "1999年", city: "广东汕头", honors: "中国洗护行业领军企业", reputation: "产品多样化，适合各种发质，价格亲民，市场占有率高。"},
        {name: "舒蕾", logo: "logos/shampoo/shulei.png", description: "专注于秀发护理的品牌。", founded: "1996年", city: "湖北武汉", honors: "中国秀发护理知名品牌", reputation: "秀发护理专业，产品温和有效，价格适中，深受女性消费者喜爱。"},
        {name: "好迪", logo: "logos/shampoo/haodi.png", description: "知名洗护发品牌，以焗油膏闻名。", founded: "1992年", city: "广东广州", honors: "中国焗油膏领导品牌", reputation: "焗油膏效果好，深层滋养，价格亲民，口碑极佳。"},
        {name: "迪彩", logo: "logos/shampoo/dicai.png", description: "专注于染发和护发的品牌。", founded: "1998年", city: "广东广州", honors: "中国染发护发知名品牌", reputation: "染发产品温和，护发效果好，价格适中，深受消费者信赖。"},
        {name: "飘影", logo: "logos/shampoo/piaoying.png", description: "时尚洗护发品牌，产品创新。", founded: "1996年", city: "广东汕头", honors: "中国洗护行业创新品牌", reputation: "产品创新，体验感好，价格适中，年轻消费者喜爱。"},
        {name: "章华", logo: "logos/shampoo/zhanghua.png", description: "专注于染发和护发的品牌。", founded: "1981年", city: "浙江温州", honors: "中国染发行业领军企业", reputation: "染发产品品质卓越，温和不刺激，口碑极佳。"},
        {name: "澳宝", logo: "logos/shampoo/aobao.png", description: "专注于香氛洗护的品牌。", founded: "1994年", city: "广东珠海", honors: "中国香氛洗护知名品牌", reputation: "香氛持久，洗护效果好，价格适中，深受年轻女性喜爱。"},
        {name: "卫新", logo: "logos/shampoo/weixin.png", description: "专注于衣物洗护的品牌。", founded: "2000年", city: "广东广州", honors: "中国衣物洗护知名品牌", reputation: "衣物洗护专业，清洁效果好，价格适中，家庭必备。"},
        {name: "100年润发", logo: "logos/shampoo/100nianrunfa.png", description: "专注于中药洗护的品牌。", founded: "2003年", city: "浙江杭州", honors: "中国中药洗护知名品牌", reputation: "中药配方，滋养修护，价格适中，口碑良好。"},
        {name: "康王", logo: "logos/shampoo/kangwang.png", description: "专注于去屑的洗护品牌。", founded: "1993年", city: "云南昆明", honors: "中国去屑领导品牌", reputation: "去屑效果显著，专业可靠，深受头屑困扰者喜爱。"},
        {name: "雨洁", logo: "logos/shampoo/yujie.png", description: "专注于去屑的洗护品牌。", founded: "2001年", city: "广东广州", honors: "中国去屑知名品牌", reputation: "去屑效果好，价格亲民，性价比高。"},
        {name: "索芙特", logo: "logos/shampoo/suofute.png", description: "专注于功能性洗护的品牌。", founded: "1993年", city: "广西梧州", honors: "中国功能性洗护知名品牌", reputation: "功能性强，效果明显，价格适中，口碑良好。"},
        {name: "花世界", logo: "logos/shampoo/huashijie.png", description: "专注于女性洗护的品牌。", founded: "1997年", city: "广东广州", honors: "中国女性洗护知名品牌", reputation: "女性护理专业，温和不刺激，价格适中，深受女性消费者喜爱。"},
        {name: "滋采", logo: "logos/shampoo/zicai.png", description: "专注于天然洗护的品牌。", founded: "1999年", city: "广东广州", honors: "中国天然洗护知名品牌", reputation: "天然配方，温和不刺激，价格亲民，适合全家使用。"},
        {name: "阿祖秀", logo: "logos/shampoo/azuoxiu.png", description: "专注于修复受损发质的品牌。", founded: "2018年", city: "上海", honors: "中国护发新锐品牌", reputation: "修复受损发质效果好，价格适中，年轻消费者喜爱。"},
        {name: "柏丽丝", logo: "logos/shampoo/bailisi.png", description: "专注于造型和洗护的品牌。", founded: "1998年", city: "广东广州", honors: "中国造型洗护知名品牌", reputation: "造型效果好，洗护合一，价格适中，适合追求时尚的年轻人。"}
    ],
        "奶制品": [
        {name: "天友", logo: "logos/milk/tianyou.png", description: "西南地区知名奶制品品牌。", founded: "1931年", city: "重庆", honors: "中国名牌产品", reputation: "西南地区知名品牌，产品种类丰富，新鲜度高，口感好。"},
        {name: "天润", logo: "logos/milk/tianrun.png", description: "新疆特色奶制品品牌。", founded: "1999年", city: "新疆乌鲁木齐", honors: "新疆著名商标", reputation: "新疆优质奶源，产品特色鲜明，口感醇厚，深受消费者喜爱。"},
        {name: "欧亚", logo: "logos/milk/ouya.png", description: "云南知名奶制品品牌。", founded: "1992年", city: "云南昆明", honors: "云南名牌产品", reputation: "云南高原奶源，产品新鲜，口感纯正，性价比高。"},
        {name: "辉山", logo: "logos/milk/huishan.png", description: "东北地区知名奶制品品牌。", founded: "1951年", city: "辽宁沈阳", honors: "中国名牌产品", reputation: "东北优质奶源，产品种类丰富，品质稳定，口碑良好。"},
        {name: "银桥", logo: "logos/milk/yinqiao.png", description: "西北地区知名奶制品品牌。", founded: "1978年", city: "陕西西安", honors: "中国名牌产品", reputation: "西北优质奶源，产品新鲜，价格亲民，深受当地消费者喜爱。"},
        {name: "皇氏", logo: "logos/milk/huangshi.png", description: "广西知名奶制品品牌。", founded: "2001年", city: "广西南宁", honors: "广西著名商标", reputation: "广西特色奶制品，口感独特，产品创新，年轻消费者喜爱。"},
        {name: "子承乳业", logo: "logos/milk/zichengruye.png", description: "专注于有机奶制品的品牌。", founded: "2010年", city: "内蒙古呼和浩特", honors: "中国有机奶知名品牌", reputation: "有机奶源，健康安全，品质卓越，高端消费者首选。"},
        {name: "完达山", logo: "logos/milk/wandashan.png", description: "黑龙江知名奶制品品牌。", founded: "1958年", city: "黑龙江哈尔滨", honors: "中国名牌产品", reputation: "东北优质奶源，历史悠久，品质可靠，消费者信赖。"},
        {name: "佳宝", logo: "logos/milk/jiabao.png", description: "山东知名奶制品品牌。", founded: "1930年", city: "山东济南", honors: "山东著名商标", reputation: "历史悠久，产品种类丰富，口感好，价格亲民。"},
        {name: "雪兰", logo: "logos/milk/xuelan.png", description: "云南知名奶制品品牌。", founded: "1990年", city: "云南昆明", honors: "云南名牌产品", reputation: "云南高原奶源，产品新鲜，口感纯正，深受当地消费者喜爱。"},
        {name: "新希望", logo: "logos/milk/xinxihope.png", description: "全国知名奶制品品牌。", founded: "1998年", city: "四川成都", honors: "中国乳业领军企业", reputation: "全国性品牌，产品线全面，品质稳定，市场占有率高。"},
        {name: "乍甸", logo: "logos/milk/zadian.png", description: "云南特色奶制品品牌。", founded: "1953年", city: "云南红河", honors: "云南名牌产品", reputation: "云南特色奶源，产品新鲜，口感醇厚，当地消费者喜爱。"},
        {name: "海河", logo: "logos/milk/haihe.png", description: "天津知名奶制品品牌。", founded: "1957年", city: "天津", honors: "天津著名商标", reputation: "天津老品牌，产品种类丰富，价格亲民，口碑良好。"},
        {name: "长富", logo: "logos/milk/changfu.png", description: "福建知名奶制品品牌。", founded: "1998年", city: "福建福州", honors: "福建著名商标", reputation: "福建优质奶源，产品新鲜，口感好，深受当地消费者喜爱。"},
        {name: "蝶泉", logo: "logos/milk/diequan.png", description: "云南知名奶制品品牌。", founded: "1956年", city: "云南大理", honors: "云南名牌产品", reputation: "云南高原奶源，产品特色鲜明，口感醇厚，历史悠久。"},
        {name: "山西古城", logo: "logos/milk/shanxigucheng.png", description: "山西知名奶制品品牌。", founded: "1982年", city: "山西朔州", honors: "山西著名商标", reputation: "山西地区知名品牌，产品种类丰富，价格亲民，当地消费者喜爱。"},
        {name: "好一多", logo: "logos/milk/haoyiduo.png", description: "贵州知名奶制品品牌。", founded: "2001年", city: "贵州贵阳", honors: "贵州著名商标", reputation: "贵州高原奶源，产品新鲜，口感好，深受当地消费者喜爱。"},
        {name: "光明", logo: "logos/milk/guangming.png", description: "全国知名奶制品品牌。", founded: "1956年", city: "上海", honors: "中国乳业领军企业", reputation: "全国性品牌，产品线全面，品质稳定，深受消费者信赖。"},
        {name: "花花牛", logo: "logos/milk/huahuaniu.png", description: "河南知名奶制品品牌。", founded: "1955年", city: "河南郑州", honors: "河南著名商标", reputation: "河南地区知名品牌，产品种类丰富，价格亲民，当地消费者喜爱。"},
        {name: "西域春", logo: "logos/milk/xiyuchun.png", description: "新疆特色奶制品品牌。", founded: "2005年", city: "新疆昌吉", honors: "新疆著名商标", reputation: "新疆优质奶源，产品特色鲜明，口感醇厚，深受消费者喜爱。"},
        {name: "博农", logo: "logos/milk/bonong.png", description: "河南知名奶制品品牌。", founded: "1958年", city: "河南焦作", honors: "河南著名商标", reputation: "河南地区知名品牌，产品新鲜，口感好，口碑良好。"},
        {name: "维记", logo: "logos/milk/weiji.png", description: "广东知名奶制品品牌。", founded: "1940年", city: "广东广州", honors: "广东著名商标", reputation: "广东老品牌，产品种类丰富，口感好，深受当地消费者喜爱。"},
        {name: "香满楼", logo: "logos/milk/xiangmanlou.png", description: "广东知名奶制品品牌。", founded: "1982年", city: "广东广州", honors: "广东著名商标", reputation: "广东地区知名品牌，产品新鲜，口感好，深受当地消费者喜爱。"},
        {name: "百富露", logo: "logos/milk/baifulu.png", description: "广东知名奶制品品牌。", founded: "1992年", city: "广东佛山", honors: "广东著名商标", reputation: "广东地区知名品牌，产品种类丰富，价格亲民，当地消费者喜爱。"},
        {name: "卫岗", logo: "logos/milk/weigang.png", description: "江苏知名奶制品品牌。", founded: "1928年", city: "江苏南京", honors: "中国名牌产品", reputation: "历史悠久，产品种类丰富，品质可靠，深受消费者信赖。"},
        {name: "小西牛", logo: "logos/milk/xiaoxiniu.png", description: "青海特色奶制品品牌。", founded: "2002年", city: "青海西宁", honors: "青海著名商标", reputation: "青海高原奶源，产品特色鲜明，口感醇厚，深受消费者喜爱。"},
        {name: "天露", logo: "logos/milk/tianlu.png", description: "甘肃知名奶制品品牌。", founded: "1998年", city: "甘肃白银", honors: "甘肃著名商标", reputation: "甘肃地区知名品牌，产品新鲜，口感好，当地消费者喜爱。"},
        {name: "圣湖", logo: "logos/milk/shenghu.png", description: "青海特色奶制品品牌。", founded: "2004年", city: "青海西宁", honors: "青海著名商标", reputation: "青海高原奶源，产品特色鲜明，口感醇厚，深受消费者喜爱。"},
        {name: "夏进", logo: "logos/milk/xiajin.png", description: "宁夏知名奶制品品牌。", founded: "1994年", city: "宁夏吴忠", honors: "宁夏著名商标", reputation: "宁夏地区知名品牌，产品新鲜，口感好，当地消费者喜爱。"},
        {name: "旺旺", logo: "logos/milk/wangwang.png", description: "全国知名食品饮料品牌。", founded: "1983年", city: "台湾台北", honors: "中国食品行业领军企业", reputation: "产品种类丰富，口感好，包装可爱，深受儿童和年轻人喜爱。"},
        {name: "德亚", logo: "logos/milk/deya.png", description: "德国奶源中国品牌。", founded: "2012年", city: "上海", honors: "中国进口奶领导品牌", reputation: "德国优质奶源，品质卓越，包装精美，高端消费者喜爱。"},
        {name: "金河", logo: "logos/milk/jinhe.png", description: "宁夏知名奶制品品牌。", founded: "1979年", city: "宁夏银川", honors: "宁夏著名商标", reputation: "宁夏地区知名品牌，产品种类丰富，价格亲民，当地消费者喜爱。"},
        {name: "燕塘", logo: "logos/milk/yantang.png", description: "广东知名奶制品品牌。", founded: "1956年", city: "广东广州", honors: "广东著名商标", reputation: "广东老品牌，产品新鲜，口感好，深受当地消费者喜爱。"},
        {name: "风行", logo: "logos/milk/fengxing.png", description: "广东知名奶制品品牌。", founded: "1927年", city: "广东广州", honors: "广东著名商标", reputation: "历史悠久，产品种类丰富，品质可靠，深受消费者信赖。"},
        {name: "华中农业大学-水牛鲜奶", logo: "logos/milk/huazhongshuiniu.png", description: "高校研发的特色奶制品。", founded: "2000年", city: "湖北武汉", honors: "高校特色产品", reputation: "高校研发，科技含量高，水牛鲜奶特色鲜明，营养丰富，健康安全。"},
     ],   
        "饮料": [
        {name: "农夫山泉", logo: "logos/beverage/nongfuspring.png", description: "全国知名饮用水品牌。", founded: "1996年", city: "浙江杭州", honors: "中国饮料行业领军企业", reputation: "天然矿泉水，水质优良，口感好，品牌形象好，消费者信赖。"},
        {name: "娃哈哈", logo: "logos/beverage/wahaha.png", description: "全国知名食品饮料品牌。", founded: "1987年", city: "浙江杭州", honors: "中国饮料行业领军企业", reputation: "产品种类丰富，口感好，价格亲民，市场占有率高。"},
        {name: "椰树", logo: "logos/beverage/yashu.png", description: "海南特色饮品品牌。", founded: "1956年", city: "海南海口", honors: "中国名牌产品", reputation: "海南特色，椰汁口感纯正，历史悠久，消费者喜爱。"},
        {name: "冰泉", logo: "logos/beverage/bingquan.png", description: "广西特色饮品品牌。", founded: "1956年", city: "广西梧州", honors: "广西著名商标", reputation: "广西特色，豆浆晶历史悠久，口感好，营养丰富。"},
        {name: "天府可乐", logo: "logos/beverage/tianfukele.png", description: "重庆特色可乐品牌。", founded: "1936年", city: "重庆", honors: "中国历史文化名饮", reputation: "中药配方可乐，口感独特，历史悠久，重庆特色，消费者怀旧情结浓厚。"},
        {name: "崂山可乐", logo: "logos/beverage/laoshnakele.png", description: "山东特色可乐品牌。", founded: "1953年", city: "山东青岛", honors: "山东著名商标", reputation: "中药配方可乐，口感独特，历史悠久，青岛特色，消费者喜爱。"},
        {name: "豆本豆", logo: "logos/beverage/doubendou.png", description: "植物蛋白饮品品牌。", founded: "2017年", city: "北京", honors: "中国植物奶新锐品牌", reputation: "植物蛋白饮品，健康营养，口感好，适合素食者和健康人群。"},
        {name: "汇源", logo: "logos/beverage/huiyuan.png", description: "全国知名果汁品牌。", founded: "1992年", city: "北京", honors: "中国果汁行业领军企业", reputation: "果汁含量高，口感纯正，产品线全面，深受消费者喜爱。"},
        {name: "RIO", logo: "logos/beverage/rio.png", description: "预调鸡尾酒品牌。", founded: "2003年", city: "上海", honors: "中国预调酒领导品牌", reputation: "预调鸡尾酒，口感好，包装时尚，年轻消费者喜爱。"},
        {name: "李子园", logo: "logos/beverage/liziyuan.png", description: "全国知名含乳饮料品牌。", founded: "1994年", city: "浙江金华", honors: "浙江著名商标", reputation: "含乳饮料，口感好，价格亲民，深受儿童和年轻人喜爱。"},
        {name: "菲诺", logo: "logos/beverage/feinuo.png", description: "椰子制品品牌。", founded: "2015年", city: "云南昆明", honors: "中国椰子制品新锐品牌", reputation: "椰子制品，口感好，品质高，年轻消费者喜爱。"},
        {name: "津威", logo: "logos/beverage/jinwei.png", description: "广东特色乳酸菌饮品品牌。", founded: "1990年", city: "广东惠州", honors: "广东著名商标", reputation: "乳酸菌饮品，口感好，有助于消化，儿童和家庭喜爱。"},
        {name: "霞光", logo: "logos/beverage/xaguang.png", description: "果酒品牌。", founded: "2008年", city: "山东烟台", honors: "中国果酒知名品牌", reputation: "果酒口感好，度数低，适合女性消费者，包装精美。"},
        {name: "健力宝", logo: "logos/beverage/jianlibao.png", description: "全国知名运动饮料品牌。", founded: "1984年", city: "广东佛山", honors: "中国运动饮料领导品牌", reputation: "运动饮料，补充能量，口感好，历史悠久，消费者喜爱。"}
       ], 
        "调味品": [// 调味品
        {name: "莲花味精", logo: "logos/condiment/lianhuaweijing.png", description: "全国知名味精品牌。", founded: "1983年", city: "河南项城", honors: "中国名牌产品", reputation: "味精品质好，鲜味纯正，历史悠久，消费者信赖。"},
        {name: "国泰味精", logo: "logos/condiment/guotaiweijing.png", description: "知名味精品牌。", founded: "1995年", city: "山东济宁", honors: "山东著名商标", reputation: "味精品质好，鲜味纯正，价格亲民，性价比高。"},
        {name: "天厨味精", logo: "logos/condiment/tianchuweijing.png", description: "老牌味精品牌。", founded: "1923年", city: "上海", honors: "中国历史文化名品", reputation: "历史悠久，味精品质好，鲜味纯正，消费者信赖。"},
        {name: "名扬底料", logo: "logos/condiment/mingyangdiliang.png", description: "四川火锅底料品牌。", founded: "2003年", city: "四川成都", honors: "四川著名商标", reputation: "火锅底料麻辣鲜香，口感好，深受消费者喜爱。"},
        {name: "恒顺", logo: "logos/condiment/hengshun.png", description: "江苏知名调味品品牌。", founded: "1840年", city: "江苏镇江", honors: "中国名牌产品", reputation: "镇江香醋历史悠久，品质卓越，口感好，消费者信赖。"},
        {name: "鲁花", logo: "logos/condiment/luhua.png", description: "全国知名食用油品牌。", founded: "1986年", city: "山东莱阳", honors: "中国食用油行业领军企业", reputation: "花生油品质好，香味浓郁，营养健康，消费者喜爱。"},
        {name: "正义", logo: "logos/condiment/zhengyi.png", description: "酱油品牌。", founded: "1992年", city: "广东佛山", honors: "广东著名商标", reputation: "酱油品质好，风味独特，价格亲民，性价比高。"},
        {name: "安琪酵母", logo: "logos/condiment/anqijiaomu.png", description: "全国知名酵母品牌。", founded: "1986年", city: "湖北宜昌", honors: "中国酵母行业领军企业", reputation: "酵母品质好，发酵效果好，科技含量高，消费者信赖。"},
        {name: "王守义十三香", logo: "logos/condiment/wangshouyishisanxiang.png", description: "全国知名调味品品牌。", founded: "1984年", city: "河南驻马店", honors: "中国名牌产品", reputation: "香料配方独特，调味效果好，历史悠久，消费者信赖。"},
        {name: "水塔陈醋", logo: "logos/condiment/shuitacuchen.png", description: "山西知名醋品牌。", founded: "1976年", city: "山西清徐", honors: "山西著名商标", reputation: "山西老陈醋，口感醇厚，历史悠久，消费者喜爱。"},
        {name: "保定槐茂面酱", logo: "logos/condiment/baodinghuaimaomianjiang.png", description: "河北特色调味品品牌。", founded: "1671年", city: "河北保定", honors: "中国历史文化名品", reputation: "历史悠久，面酱风味独特，品质好，当地消费者喜爱。"},
        {name: "福临门", logo: "logos/condiment/fulinmen.png", description: "全国知名食用油品牌。", founded: "2002年", city: "北京", honors: "中国食用油行业领军企业", reputation: "食用油产品线全面，品质稳定，价格适中，消费者信赖。"},
       ], 
       "方便食品": [
        // 方便食品/零食
        {name: "白象", logo: "logos/instantfood/baixiang.png", description: "全国知名方便面品牌。", founded: "1997年", city: "河南郑州", honors: "中国方便面行业领军企业", reputation: "方便面口感好，种类丰富，价格亲民，深受消费者喜爱。"},
        {name: "阿宽", logo: "logos/instantfood/akuang.png", description: "新兴方便食品品牌。", founded: "2015年", city: "四川成都", honors: "中国方便食品新锐品牌", reputation: "方便食品种类丰富，口感独特，年轻消费者喜爱。"},
        {name: "五谷道扬", logo: "logos/instantfood/wugudoyang.png", description: "方便食品品牌。", founded: "2012年", city: "北京", honors: "中国方便食品知名品牌", reputation: "方便食品健康营养，口感好，适合注重健康的消费者。"},
        {name: "幸运方便面", logo: "logos/instantfood/xingyunfangbianmian.png", description: "安徽特色方便面品牌。", founded: "1989年", city: "安徽淮北", honors: "安徽著名商标", reputation: "安徽特色，方便面口感好，历史悠久，当地消费者喜爱。"},
        {name: "好欢螺", logo: "logos/instantfood/haohuanluo.png", description: "广西特色方便食品品牌。", founded: "2015年", city: "广西柳州", honors: "中国螺蛳粉领导品牌", reputation: "螺蛳粉风味正宗，口感好，深受消费者喜爱。"},
        {name: "泰奇", logo: "logos/instantfood/taiqi.png", description: "广东特色方便食品品牌。", founded: "1992年", city: "广东广州", honors: "广东著名商标", reputation: "八宝粥口感好，营养丰富，方便携带，消费者喜爱。"},
       ],
        "零食": [
        {name: "米老头", logo: "logos/snack/milaotou.png", description: "休闲食品品牌。", founded: "1997年", city: "四川成都", honors: "四川著名商标", reputation: "休闲食品种类丰富，口感好，价格亲民，深受儿童和年轻人喜爱。"},
        {name: "酒鬼花生", logo: "logos/snack/jiuguihuasheng.png", description: "休闲食品品牌。", founded: "1997年", city: "四川成都", honors: "四川著名商标", reputation: "花生口感酥脆，风味独特，下酒佳品，消费者喜爱。"},
        {name: "荣欣堂", logo: "logos/snack/rongxintang.png", description: "山西特色糕点品牌。", founded: "1895年", city: "山西太原", honors: "中国历史文化名品", reputation: "山西特色糕点，历史悠久，口感好，文化底蕴深厚。"},
        {name: "喜之郎", logo: "logos/snack/xizhilang.png", description: "全国知名果冻品牌。", founded: "1993年", city: "广东深圳", honors: "中国果冻行业领军企业", reputation: "果冻口感好，种类丰富，包装可爱，深受儿童和年轻人喜爱。"},
        {name: "伟龙", logo: "logos/snack/weilong.png", description: "饼干品牌。", founded: "1993年", city: "山东临沂", honors: "山东著名商标", reputation: "饼干口感好，种类丰富，价格亲民，深受消费者喜爱。"},
        {name: "运康", logo: "logos/snack/yunkang.png", description: "山西特色休闲食品品牌。", founded: "1995年", city: "山西运城", honors: "山西著名商标", reputation: "锅巴口感酥脆，风味独特，当地消费者喜爱。"},
        {name: "馋大嘴巴", logo: "logos/snack/chandazuiba.png", description: "休闲食品品牌。", founded: "2008年", city: "湖南长沙", honors: "湖南著名商标", reputation: "休闲食品种类丰富，口感好，价格亲民，年轻消费者喜爱。"},
        {name: "老香斋", logo: "logos/snack/laoxiangzhai.png", description: "上海特色糕点品牌。", founded: "1913年", city: "上海", honors: "上海著名商标", reputation: "上海特色糕点，历史悠久，口感好，文化底蕴深厚。"},
        {name: "陶陶居", logo: "logos/snack/taotaoju.png", description: "广州特色糕点品牌。", founded: "1880年", city: "广东广州", honors: "中国历史文化名品", reputation: "广州特色糕点，历史悠久，口感好，文化底蕴深厚。"},
        {name: "九度七", logo: "logos/snack/jiuduqi.png", description: "新兴休闲食品品牌。", founded: "2017年", city: "福建厦门", honors: "中国休闲食品新锐品牌", reputation: "休闲食品种类丰富，口感好，包装精美，年轻消费者喜爱。"},
        {name: "华丰", logo: "logos/snack/huafeng.png", description: "老牌方便面品牌。", founded: "1982年", city: "广东深圳", honors: "中国老牌方便面名品", reputation: "方便面历史悠久，口感好，价格亲民，消费者怀旧情结浓厚。"},
        ],
        "米面粮油": [
        {name: "陈克明", logo: "logos/grain/chenkeming.png", description: "全国知名挂面品牌。", founded: "1984年", city: "湖南南县", honors: "中国挂面行业领军企业", reputation: "挂面品质好，种类丰富，口感好，消费者信赖。"},
        {name: "思源", logo: "logos/grain/siyuan.png", description: "大米品牌。", founded: "2005年", city: "江西南昌", honors: "江西著名商标", reputation: "大米品质好，口感软糯，营养健康，消费者喜爱。"},
        {name: "螺玛", logo: "logos/grain/luoma.png", description: "米粉品牌。", founded: "2010年", city: "广西南宁", honors: "广西著名商标", reputation: "米粉品质好，口感顺滑，适合制作各种米粉食品。"},
        {name: "银鸥好食", logo: "logos/grain/yinouhaoshi.png", description: "面粉品牌。", founded: "1998年", city: "广东湛江", honors: "广东著名商标", reputation: "面粉品质好，适合制作各种面食，家庭烘焙首选。"},
        {name: "福临门", logo: "logos/grain/fulinmen.png", description: "全国知名米面粮油品牌。", founded: "2002年", city: "北京", honors: "中国粮油行业领军企业", reputation: "产品线全面，品质稳定，价格适中，消费者信赖。"},
        {name: "旌晶", logo: "logos/grain/jingjing.png", description: "方便食品品牌。", founded: "1985年", city: "四川成都", honors: "四川著名商标", reputation: "方便食品种类丰富，营养健康，适合早餐和旅行。"},
        {name: "中粮", logo: "logos/grain/zhongliang.png", description: "全国知名粮油品牌。", founded: "1949年", city: "北京", honors: "中国粮油行业领军企业", reputation: "央企背景，产品线全面，品质稳定，消费者高度信赖。"}
    ],
    "香皂类": [
        {name: "蜂花", logo: "logos/soap/fenghua.png", description: "上海老牌日化品牌。", founded: "1985年", city: "上海", honors: "中国名牌产品", reputation: "上海老品牌，产品种类丰富，价格亲民，品质可靠，消费者信赖。"},
        {name: "上海硫磺皂", logo: "logos/soap/shanghailiuhuang.png", description: "上海传统药皂品牌。", founded: "1923年", city: "上海", honors: "中国历史文化名品", reputation: "历史悠久，具有杀菌除螨功效，价格亲民，深受消费者喜爱。"},
        {name: "澳雪", logo: "logos/soap/aoxue.png", description: "广东知名日化品牌。", founded: "1994年", city: "广东汕头", honors: "广东著名商标", reputation: "沐浴露系列产品丰富，香气持久，价格适中，深受家庭消费者喜爱。"},
        {name: "六神", logo: "logos/soap/liushen.png", description: "上海知名个人护理品牌。", founded: "1990年", city: "上海", honors: "中国名牌产品", reputation: "花露水清凉提神，沐浴露清爽舒适，夏季必备，消费者信赖。"},
        {name: "上海药皂", logo: "logos/soap/shanghaiyaozao.png", description: "上海传统药皂品牌。", founded: "1907年", city: "上海", honors: "中国历史文化名品", reputation: "历史悠久，具有杀菌消毒功效，价格亲民，品质可靠，消费者信赖。"},
        {name: "蜂花檀香皂", logo: "logos/soap/fenghuatangxiang.png", description: "上海传统香皂品牌。", founded: "1928年", city: "上海", honors: "中国历史文化名品", reputation: "历史悠久，檀香味浓郁持久，品质卓越，文化底蕴深厚，消费者喜爱。"},
        {name: "上海芦荟皂", logo: "logos/soap/shanghaihuisu.png", description: "上海特色香皂品牌。", founded: "1995年", city: "上海", honors: "上海著名商标", reputation: "添加芦荟成分，温和滋润，适合敏感肌肤，价格适中，消费者喜爱。"},
        {name: "纳爱斯香皂", logo: "logos/soap/naaixiangzao.png", description: "浙江知名日化品牌。", founded: "1994年", city: "浙江丽水", honors: "中国名牌产品", reputation: "香皂清洁力强，香气宜人，价格亲民，市场占有率高，消费者喜爱。"},
        {name: "六神香皂", logo: "logos/soap/liushenxiangzao.png", description: "六神旗下香皂品牌。", founded: "1995年", city: "上海", honors: "中国著名商标", reputation: "清凉舒爽，具有除菌功效，夏季使用舒适，消费者喜爱。"}
    ],
    "牙膏": [
        {name: "白玉", logo: "logos/toothpaste/baiyu.png", description: "上海老牌牙膏品牌。", founded: "1912年", city: "上海", honors: "中国历史文化名品", reputation: "历史悠久，价格亲民，口感温和，清洁效果好，消费者信赖。"},
        {name: "冷酸灵", logo: "logos/toothpaste/lengsuanling.png", description: "重庆知名抗敏感牙膏品牌。", founded: "1956年", city: "重庆", honors: "中国名牌产品", reputation: "抗敏感功效显著，口感清凉，品质可靠，消费者信赖。"},
        {name: "黑妹", logo: "logos/toothpaste/heimei.png", description: "广东知名牙膏品牌。", founded: "1986年", city: "广东广州", honors: "广东著名商标", reputation: "双重薄荷口味，清新口气，价格适中，消费者喜爱。"},
        {name: "田七", logo: "logos/toothpaste/tianqi.png", description: "广西知名牙膏品牌。", founded: "1945年", city: "广西梧州", honors: "广西著名商标", reputation: "中药配方，清凉止血，历史悠久，消费者信赖。"},
        {name: "两面针", logo: "logos/toothpaste/liangmianzhen.png", description: "广西知名中药牙膏品牌。", founded: "1941年", city: "广西柳州", honors: "中国名牌产品", reputation: "中药配方，消炎止血，历史悠久，品质可靠，消费者信赖。"},
        {name: "六必治", logo: "logos/toothpaste/liubizhi.png", description: "天津知名牙膏品牌。", founded: "1911年", city: "天津", honors: "中国历史文化名品", reputation: "历史悠久，中药配方，口气清新，品质可靠，消费者信赖。"},
        {name: "松达", logo: "logos/toothpaste/songda.png", description: "福建知名牙膏品牌。", founded: "1964年", city: "福建漳州", honors: "福建著名商标", reputation: "草本配方，温和不刺激，适合全家使用，消费者喜爱。"},
        {name: "白云山", logo: "logos/toothpaste/baiyunshan.png", description: "广州知名医药企业旗下口腔护理品牌。", founded: "1970年", city: "广东广州", honors: "中国名牌产品", reputation: "医药背景，功效性强，品质可靠，消费者信赖。"},
        {name: "芳草", logo: "logos/toothpaste/fangcao.png", description: "安徽知名牙膏品牌。", founded: "1958年", city: "安徽合肥", honors: "安徽著名商标", reputation: "双重薄荷口味，价格亲民，清洁效果好，消费者喜爱。"},
        {name: "纳爱斯", logo: "logos/toothpaste/naaisi.png", description: "浙江知名日化品牌。", founded: "1994年", city: "浙江丽水", honors: "中国名牌产品", reputation: "牙膏种类丰富，口感好，价格适中，市场占有率高，消费者喜爱。"},
        {name: "云南白药", logo: "logos/toothpaste/yunnanbaiyao.png", description: "云南知名医药企业旗下口腔护理品牌。", founded: "1902年", city: "云南昆明", honors: "中国名牌产品", reputation: "医药背景，止血消炎功效显著，高端品质，消费者高度信赖。"},
        {name: "舒客", logo: "logos/toothpaste/suker.png", description: "广州知名口腔护理品牌。", founded: "2006年", city: "广东广州", honors: "中国口腔护理新锐品牌", reputation: "产品线全面，包装时尚，适合年轻消费者，市场认可度高。"},
        {name: "好易康", logo: "logos/toothpaste/haoyikang.png", description: "福建知名口腔护理品牌。", founded: "2010年", city: "福建厦门", honors: "中国口腔护理知名品牌", reputation: "生物活性成分，科技含量高，功效显著，消费者喜爱。"},
        {name: "康齿灵", logo: "logos/toothpaste/kangchiling.png", description: "辽宁知名口腔护理品牌。", founded: "1978年", city: "辽宁大连", honors: "辽宁著名商标", reputation: "防蛀护齿功效好，价格适中，适合家庭使用，消费者喜爱。"},
        {name: "四七", logo: "logos/toothpaste/siqi.png", description: "云南知名牙膏品牌。", founded: "1992年", city: "云南昆明", honors: "云南著名商标", reputation: "中药配方，清凉舒适，价格适中，消费者喜爱。"},
        {name: "片仔癀", logo: "logos/toothpaste/pianzaihuang.png", description: "福建知名医药企业旗下口腔护理品牌。", founded: "1999年", city: "福建漳州", honors: "中国名牌产品", reputation: "医药背景，消炎止血功效显著，高端品质，消费者信赖。"},
        {name: "奥乐v", logo: "logos/toothpaste/aolev.png", description: "专业儿童口腔护理品牌。", founded: "2010年", city: "广东深圳", honors: "中国儿童口腔护理领导品牌", reputation: "专为儿童设计，安全温和，防蛀效果好，家长信赖。"},
        {name: "草珊瑚", logo: "logos/toothpaste/caoshanhu.png", description: "江西知名牙膏品牌。", founded: "1994年", city: "江西南昌", honors: "江西著名商标", reputation: "草本配方，清新口气，价格适中，消费者喜爱。"}
    ],
    "洗衣粉": [
        {name: "活力28", logo: "logos/detergent/huoli28.png", description: "湖北知名洗衣粉品牌。", founded: "1950年", city: "湖北荆州", honors: "中国名牌产品", reputation: "老品牌，去污力强，价格亲民，家庭主妇首选。"},
        {name: "白猫", logo: "logos/detergent/baimao.png", description: "上海老牌日化品牌。", founded: "1948年", city: "上海", honors: "中国历史文化名品", reputation: "洗洁精效果好，温和不刺激，老品牌，消费者信赖。"},
        {name: "立白", logo: "logos/detergent/libai.png", description: "广东知名日化品牌。", founded: "1994年", city: "广东广州", honors: "中国名牌产品", reputation: "产品线丰富，去污力强，价格适中，市场占有率高，消费者喜爱。"},
        {name: "裕华", logo: "logos/detergent/yuhua.png", description: "河北知名日化品牌。", founded: "1985年", city: "河北石家庄", honors: "河北著名商标", reputation: "洗衣粉去污力强，价格亲民，适合普通家庭使用，消费者喜爱。"},
        {name: "纳爱斯", logo: "logos/detergent/naaisi.png", description: "浙江知名日化品牌。", founded: "1994年", city: "浙江丽水", honors: "中国名牌产品", reputation: "产品线全面，品质稳定，价格适中，消费者信赖。"},
        {name: "雕牌", logo: "logos/detergent/diaopai.png", description: "纳爱斯集团旗下洗涤品牌。", founded: "1997年", city: "浙江丽水", honors: "中国名牌产品", reputation: "洗衣粉去污力强，价格亲民，广告深入人心，消费者喜爱。"},
        {name: "红卫", logo: "logos/detergent/hongwei.png", description: "上海传统肥皂品牌。", founded: "1958年", city: "上海", honors: "上海著名商标", reputation: "肥皂清洁力强，经久耐用，老品牌，消费者信赖。"},
        {name: "奇强", logo: "logos/detergent/qiqiang.png", description: "山西知名日化品牌。", founded: "1992年", city: "山西运城", honors: "中国名牌产品", reputation: "洗衣粉去污力强，价格适中，适合家庭使用，消费者喜爱。"},
        {name: "金鱼", logo: "logos/detergent/jinyu.png", description: "山东知名日化品牌。", founded: "1950年", city: "山东青岛", honors: "山东著名商标", reputation: "洗涤产品种类丰富，去污力强，价格适中，消费者喜爱。"},
        {name: "绿伞", logo: "logos/detergent/lvsan.png", description: "北京知名日化品牌。", founded: "1993年", city: "北京", honors: "北京著名商标", reputation: "家居清洁产品种类丰富，环保配方，清洁效果好，消费者喜爱。"},
        {name: "红玫瑰", logo: "logos/detergent/hongmeigui.png", description: "上海传统肥皂品牌。", founded: "1956年", city: "上海", honors: "上海著名商标", reputation: "肥皂品质好，价格亲民，老品牌，消费者信赖。"},
        {name: "久荣", logo: "logos/detergent/jiurong.png", description: "江苏知名日化品牌。", founded: "1996年", city: "江苏南京", honors: "江苏著名商标", reputation: "家居清洁产品种类丰富，清洁效果好，价格适中，消费者喜爱。"},
        {name: "超能", logo: "logos/detergent/chaoneng.png", description: "纳爱斯集团旗下高端洗涤品牌。", founded: "2006年", city: "浙江丽水", honors: "中国名牌产品", reputation: "天然配方，温和不刺激，适合手洗和机洗，高端品质，消费者喜爱。"},
        {name: "好爸爸", logo: "logos/detergent/haobaba.png", description: "立白集团旗下高端洗涤品牌。", founded: "2012年", city: "广东广州", honors: "中国高端洗涤领导品牌", reputation: "专为儿童衣物设计，温和不刺激，除菌效果好，家长信赖。"},
        {name: "马牌", logo: "logos/detergent/mapai.png", description: "山东知名日化品牌。", founded: "1966年", city: "山东青岛", honors: "山东著名商标", reputation: "鞋油效果好，护理皮革，老品牌，消费者信赖。"},
        {name: "大运河肥皂", logo: "logos/detergent/dayunhefeizao.png", description: "河北传统肥皂品牌。", founded: "1958年", city: "河北沧州", honors: "河北著名商标", reputation: "肥皂去污力强，经久耐用，价格亲民，消费者喜爱。"},
        {name: "扇牌", logo: "logos/detergent/shanpai.png", description: "上海传统日化品牌。", founded: "1925年", city: "上海", honors: "中国历史文化名品", reputation: "历史悠久，肥皂品质好，清洁力强，消费者信赖。"},
        {name: "帮洁洁厕灵", logo: "logos/detergent/bangjiejieceling.png", description: "河北知名洁厕品牌。", founded: "1997年", city: "河北石家庄", honors: "中国厕所清洁领导品牌", reputation: "强效除垢，除菌消毒，价格适中，消费者喜爱。"},
        {name: "超威洁厕灵", logo: "logos/detergent/chaoweijieceling.png", description: "立白集团旗下洁厕品牌。", founded: "2002年", city: "广东广州", honors: "中国名牌产品", reputation: "强效除垢，持久清香，除菌消毒，消费者信赖。"}
    ],
    "卫生纸巾": [
        {name: "洁柔", logo: "logos/tissue/jierou.png", description: "广东知名纸巾品牌。", founded: "1999年", city: "广东中山", honors: "中国名牌产品", reputation: "纸巾柔软亲肤，吸水性强，品质稳定，消费者信赖。"},
        {name: "力邦", logo: "logos/tissue/libang.png", description: "河北知名纸巾品牌。", founded: "2005年", city: "河北保定", honors: "河北著名商标", reputation: "纸巾质量好，价格亲民，适合家庭使用，消费者喜爱。"},
        {name: "雨森", logo: "logos/tissue/yusen.png", description: "河北知名纸巾品牌。", founded: "1999年", city: "河北石家庄", honors: "河北著名商标", reputation: "纸巾种类丰富，性价比高，消费者喜爱。"},
        {name: "斑布", logo: "logos/tissue/banbu.png", description: "四川知名竹浆纸品牌。", founded: "2012年", city: "四川成都", honors: "中国竹浆纸领导品牌", reputation: "竹浆原料，环保健康，纸质坚韧，消费者喜爱。"},
        {name: "心相印", logo: "logos/tissue/xinxiangyin.png", description: "恒安集团旗下知名纸巾品牌。", founded: "1985年", city: "福建晋江", honors: "中国名牌产品", reputation: "纸巾柔软舒适，种类丰富，市场占有率高，消费者信赖。"},
        {name: "洁云", logo: "logos/tissue/jieyun.png", description: "上海知名纸巾品牌。", founded: "1996年", city: "上海", honors: "上海著名商标", reputation: "纸巾品质好，价格适中，适合家庭使用，消费者喜爱。"},
        {name: "舒莱", logo: "logos/tissue/shulai.png", description: "河南知名卫生巾品牌。", founded: "1998年", city: "河南漯河", honors: "河南著名商标", reputation: "卫生巾舒适透气，吸收性好，价格亲民，消费者喜爱。"},
        {name: "倍舒特", logo: "logos/tissue/beishute.png", description: "北京知名卫生巾品牌。", founded: "1998年", city: "北京", honors: "中国卫生巾行业知名品牌", reputation: "卫生巾吸收性好，防侧漏，舒适透气，消费者信赖。"},
        {name: "ABC", logo: "logos/tissue/abc.png", description: "广东知名卫生巾品牌。", founded: "1998年", city: "广东佛山", honors: "中国卫生巾行业知名品牌", reputation: "卫生巾舒适透气，清凉配方，年轻消费者喜爱。"},
        {name: "凸凸棉", logo: "logos/tissue/tutumian.png", description: "河南知名卫生巾品牌。", founded: "2015年", city: "河南漯河", honors: "中国新锐卫生巾品牌", reputation: "卫生巾纯棉材质，舒适透气，年轻消费者喜爱。"},
        {name: "自由点", logo: "logos/tissue/ziyouxian.png", description: "重庆知名卫生巾品牌。", founded: "2002年", city: "重庆", honors: "中国卫生巾行业知名品牌", reputation: "卫生巾舒适透气，吸收性好，消费者信赖。"},
        {name: "洁伶", logo: "logos/tissue/jieling.png", description: "广西知名卫生巾品牌。", founded: "1993年", city: "广西桂林", honors: "广西著名商标", reputation: "卫生巾舒适透气，价格亲民，消费者喜爱。"},
        {name: "七度空间", logo: "logos/tissue/qidukongjian.png", description: "恒安集团旗下高端卫生巾品牌。", founded: "2002年", city: "福建晋江", honors: "中国名牌产品", reputation: "卫生巾舒适透气，种类丰富，年轻消费者喜爱。"},
        {name: "洁婷", logo: "logos/tissue/jieting.png", description: "湖北知名卫生巾品牌。", founded: "1997年", city: "湖北武汉", honors: "湖北著名商标", reputation: "卫生巾舒适透气，吸收性好，消费者信赖。"},
        {name: "喜玫瑰", logo: "logos/tissue/ximeigui.png", description: "湖南知名卫生巾品牌。", founded: "2010年", city: "湖南长沙", honors: "湖南著名商标", reputation: "卫生巾舒适透气，性价比高，消费者喜爱。"},
        {name: "丽邦", logo: "logos/tissue/libang.png", description: "河北知名纸巾品牌。", founded: "1995年", city: "河北保定", honors: "河北著名商标", reputation: "纸巾质量好，价格亲民，适合家庭使用，消费者喜爱。"},
        {name: "爱舒乐", logo: "logos/tissue/aishule.png", description: "辽宁知名成人护理品牌。", founded: "2008年", city: "辽宁大连", honors: "中国成人护理行业知名品牌", reputation: "成人纸尿裤舒适透气，吸收性好，老年人信赖。"},
        {name: "益小小", logo: "logos/tissue/yixiaoxiao.png", description: "浙江知名婴儿护理品牌。", founded: "2016年", city: "浙江杭州", honors: "中国婴儿护理新锐品牌", reputation: "婴儿纸尿裤舒适透气，吸收性好，家长信赖。"},
        {name: "米精华", logo: "logos/tissue/mijinghua.png", description: "福建知名纸巾品牌。", founded: "2014年", city: "福建福州", honors: "福建著名商标", reputation: "纸巾柔软亲肤，吸水性强，性价比高，消费者喜爱。"}
    ],
    "服装": [
        {name: "鸿星尔克", description: "福建知名运动服装品牌。", founded: "2000年", city: "福建厦门", honors: "中国名牌产品", reputation: "运动服装质量好，设计时尚，价格适中，爱国情怀浓厚，消费者喜爱。"},
        {name: "贵人鸟", description: "福建知名运动服装品牌。", founded: "1987年", city: "福建晋江", honors: "中国名牌产品", reputation: "运动服装舒适耐穿，性价比高，消费者信赖。"},
        {name: "飞跃", description: "上海知名运动鞋品牌。", founded: "1931年", city: "上海", honors: "中国历史文化名品", reputation: "帆布鞋经典时尚，舒适耐穿，价格亲民，年轻人喜爱。"},
        {name: "百年双星", description: "青岛知名运动品牌。", founded: "1921年", city: "山东青岛", honors: "中国历史文化名品", reputation: "历史悠久，产品种类丰富，价格亲民，消费者信赖。"},
        {name: "足力健", description: "北京知名老年鞋品牌。", founded: "2012年", city: "北京", honors: "中国老年鞋领导品牌", reputation: "专为老年人设计，舒适安全，防滑耐磨，老年人信赖。"},
        {name: "人本", description: "浙江知名鞋类品牌。", founded: "1986年", city: "浙江温州", honors: "浙江著名商标", reputation: "帆布鞋舒适耐穿，价格亲民，年轻人喜爱。"},
        {name: "saltum", description: "广东知名休闲服装品牌。", founded: "2005年", city: "广东广州", honors: "广东著名商标", reputation: "休闲服装时尚潮流，质量好，年轻人喜爱。"},
        {name: "回力", description: "上海知名运动鞋品牌。", founded: "1927年", city: "上海", honors: "中国历史文化名品", reputation: "帆布鞋经典时尚，舒适耐穿，价格亲民，年轻人喜爱。"},
        {name: "361", description: "福建知名运动服装品牌。", founded: "2003年", city: "福建厦门", honors: "中国名牌产品", reputation: "运动服装质量好，设计时尚，价格适中，消费者喜爱。"},
        {name: "安踏", description: "福建知名运动服装品牌。", founded: "1991年", city: "福建晋江", honors: "中国名牌产品", reputation: "运动服装质量好，设计时尚，市场占有率高，消费者信赖。"},
        {name: "多威", description: "江苏知名专业跑鞋品牌。", founded: "1983年", city: "江苏昆山", honors: "中国专业跑鞋领导品牌", reputation: "专业跑鞋舒适耐穿，性能优良，运动员和跑步爱好者喜爱。"},
        {name: "三枪", description: "上海知名内衣品牌。", founded: "1937年", city: "上海", honors: "中国名牌产品", reputation: "内衣舒适透气，质量好，老品牌，消费者信赖。"},
        {name: "ST&SAT星期六", description: "广东知名女鞋品牌。", founded: "1990年", city: "广东佛山", honors: "中国女鞋行业知名品牌", reputation: "女鞋时尚优雅，舒适耐穿，年轻女性喜爱。"}
    ]
};

// 全局暴露变量，供app.js使用
window.brandData = brandData;